platform :ios, "7.0"

pod 'AFNetworking', '~> 3.0.4'
pod "SDWebImage"
pod "MBProgressHUD"
pod "MJExtension"
pod "IQKeyboardManager"

pod "SSKeychain"

pod 'libqrencode', '~> 3.4.2'
pod 'PureLayout', '~> 3.0.1'


pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'

pod 'Masonry', '~> 0.6.4'



